apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-test-flask
  labels:
    app: eks-test-flask
  namespace: default
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: eks-test-flask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eks-test-flask
    spec:
      containers:
        - image: {{ .Values.flask_app_image.repository }}:{{ .Values.flask_app_image.version }}
          imagePullPolicy: {{ .Values.flask_app_image.pullPolicy }}
          name: eks-test-flask
          ports:
          - containerPort: {{ .Values.flask_app_image.port }}
            protocol: TCP
            name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
