kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: k8s-test-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi

---
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: longhorn
#provisioner: driver.longhorn.io
#allowVolumeExpansion: true
#parameters:
#  numberOfReplicas: "3"
#  staleReplicaTimeout: "2880" # 48 hours in minutes
#  fromBackup: ""
##  diskSelector: "ssd,fast"
##  nodeSelector: "storage,fast"
##  recurringJobSelector: '[
##   {
##     "name":"snap",
##     "isGroup":true,
##   },
##   {
##     "name":"backup",
##     "isGroup":false,
##   }
##  ]'
