apiVersion: v1
kind: Service
metadata:
  name: k8s-test-flask-service
spec:
  selector:
    app: k8s-test-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.flask_app_image.port }}
      name: http
  type: LoadBalancer
